In [11]:
import numpy as np
import pandas as pd

In [12]:
data = np.array([1,2,3,3,445,6,7,7,8,8,8,86,6,6,6,6888,1])
q1 = np.percentile(data,25)
q2 = np.percentile(data,50)
q3 = np.percentile(data,75)
q1

np.float64(3.0)

In [13]:
df = pd.DataFrame({"Value":data})
df

    Value
0       1
1       2
2       3
3       3
4     445
5       6
6       7
7       7
8       8
9       8
10      8
11     86
12      6
13      6
14      6
15   6888
16      1

In [14]:
df.describe()

             Value
count    17.000000
mean    440.647059
std    1664.886180
min       1.000000
25%       3.000000
50%       6.000000
75%       8.000000
max    6888.000000

In [16]:
q1 = df.quantile(0.25)
q2 = df.quantile(0.50)
q3 = df.quantile(0.75)
q3

Value    8.0
Name: 0.75, dtype: float64

In [ ]:
IQR = q3-q1 # IQR formula
IQR

Value    5.0
dtype: float64

In [ ]:
lower = q1-(IQR*0.25)
upper = q3+(IQR*0.75)
upper

Value    11.75
dtype: float64

In [28]:
# mask = df[["Value"]]>=lower | df[["Value"]]<=upper
# print(data[mask])