In [8]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [9]:
data = {
    'Customer': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Vikas', 'Neha', 'Raj', 'Meera', 'Ankit', 'Kavya'],
    'Fruit': ['Apple', 'Orange', 'Mango', 'Apple', 'Mango', 'Banana', 'Guava', 'Mango', 'Mango', 'Grapes'],
    'Quantity': [5, 3, 10, 2, 7, 4, 6, 8, 3, 9],
    'Price_per_kg': [100, 80, 120, 100, 120, 60, 150, 120, 120, 200],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Mumbai'],
    'Payment_Method': ['UPI', 'Cash', 'Card', 'UPI', 'Cash', 'Card', 'UPI', 'Cash', 'Card', 'UPI'],
    'Day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday']
}
df = pd.DataFrame(data)
df

,Customer,Fruit,Quantity,Price_per_kg,City,Payment_Method,Day
0,Rahul,Apple,5,100,Delhi,UPI,Monday
1,Priya,Orange,3,80,Mumbai,Cash,Tuesday
2,Amit,Mango,10,120,Bangalore,Card,Wednesday
3,Sneha,Apple,2,100,Delhi,UPI,Thursday
4,Vikas,Mango,7,120,Pune,Cash,Friday
5,Neha,Banana,4,60,Mumbai,Card,Saturday
6,Raj,Guava,6,150,Delhi,UPI,Sunday
7,Meera,Mango,8,120,Bangalore,Cash,Monday
8,Ankit,Mango,3,120,Pune,Card,Tuesday
9,Kavya,Grapes,9,200,Mumbai,UPI,Wednesday

In [10]:
encoder = OneHotEncoder(sparse_output=False) 
data = encoder.fit_transform(df[["Day"]])
data
cols = encoder.get_feature_names_out()
new_data = pd.DataFrame(data,columns=cols)
new_data

,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
df.drop(["Day"], axis =1,inplace = True)
df

  Customer   Fruit  Quantity  Price_per_kg       City Payment_Method
0    Rahul   Apple         5           100      Delhi            UPI
1    Priya  Orange         3            80     Mumbai           Cash
2     Amit   Mango        10           120  Bangalore           Card
3    Sneha   Apple         2           100      Delhi            UPI
4    Vikas   Mango         7           120       Pune           Cash
5     Neha  Banana         4            60     Mumbai           Card
6      Raj   Guava         6           150      Delhi            UPI
7    Meera   Mango         8           120  Bangalore           Cash
8    Ankit   Mango         3           120       Pune           Card
9    Kavya  Grapes         9           200     Mumbai            UPI

In [16]:
final_data = pd.concat([df,new_data],axis=1)
final_data

,Customer,Fruit,Quantity,Price_per_kg,City,Payment_Method,Day_Friday,Day_Monday,Day_Saturday,Day_Sunday,Day_Thursday,Day_Tuesday,Day_Wednesday
0,Rahul,Apple,5,100,Delhi,UPI,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,Priya,Orange,3,80,Mumbai,Cash,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Amit,Mango,10,120,Bangalore,Card,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Sneha,Apple,2,100,Delhi,UPI,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Vikas,Mango,7,120,Pune,Cash,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Neha,Banana,4,60,Mumbai,Card,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,Raj,Guava,6,150,Delhi,UPI,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,Meera,Mango,8,120,Bangalore,Cash,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,Ankit,Mango,3,120,Pune,Card,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,Kavya,Grapes,9,200,Mumbai,UPI,0.0,0.0,0.0,0.0,0.0,0.0,1.0